--Deaths Table
CREATE TABLE IF NOT EXISTS public.deaths (
	iso_code varchar,
	continent varchar,
	location varchar,
	date date,
	population DOUBLE PRECISION,
	total_cases int,
	new_cases int,
	new_cases_smoothed float,
	total_deaths DOUBLE PRECISION,
	new_deaths DOUBLE PRECISION,
	new_deaths_smoothed float,
	total_cases_per_million float,
	new_cases_per_million float,
	new_cases_smoothed_per_million float,
	total_deaths_per_million float,
	new_deaths_per_million float,
	new_deaths_smoothed_per_million float,
	reproduction_rate float,
	icu_patients int,
	icu_patients_per_million float,
	hosp_patients float,
	hosp_patients_per_million float,
	weekly_icu_admissions int,
	weekly_icu_admissions_per_million float,
	weekly_hosp_admissions int,
	weekly_hosp_admissions_per_million float
)

--Vaccine table
CREATE TABLE IF NOT EXISTS public.vaccine (
	iso_code varchar,
	continent varchar,
	location varchar,
	date date,
	total_tests double precision,
	new_tests double precision,
	total_tests_per_thousand float,
	new_tests_per_thousand float,
	new_tests_smoothed double precision,
	new_tests_smoothed_per_thousand float,
	positive_rate float,
	tests_per_case float,
	test_units varchar,
	total_vaccinations double precision,
	people_vaccinated double precision,
	people_fully_vaccinated double precision,
	total_boosters double precision,
	new_vaccinations double precision,
	new_vaccinations_smoothed double precision,
	total_vaccinations_per_hundred float,
	people_vaccinated_per_hundred float,
	people_fully_vaccinated_per_hundred float,
	total_boosters_per_hundred float,
	new_vaccinations_smoothed_per_million float,
	new_people_vaccinated_smoothed double precision,
	new_people_vaccinated_smoothed_per_hundred float,
	stringency_index float,
	population_density float,
	median_age float,
	aged_65_older float,
	aged_70_older float,
	extreme_poverty float,
	cardiovasc_death_rate float,
	diabetes_prevalence float,
	female_smokers float,
	male_smokers float,
	handwashing_facilities float NULL,
	hospital_beds_per_thousand float,
	life_expetancy float,
	human_development_index float
)

--Vaccine types and manufacturers table
CREATE TABLE IF NOT EXISTS public.vac_producer (
	iso3 varchar,
	vaccine_name varchar,
	product_name varchar,
	company_name varchar,
	authorization_date date,
	start_date date,
	data_source varchar
)

--Vaccination activities table
CREATE TABLE IF NOT EXISTS public.vaccination (
	country varchar,
	iso3 varchar,
	who_region varchar,
	data_source varchar,
	date_updated date,
	total_vaccinations double precision,
	persons_vaccinated_1plus_dose double precision,
	total_vaccinations_per100 double precision,
	persons_vaccinated_1plus_dose_per100 double precision,
	persons_last_dose double precision,
	persons_last_dose_per100 double precision,
	vaccines_used varchar,
	first_vaccine_date date,
	number_vaccines_types_used int,
	persons_booster_add_dose double precision,
	persons_booster_add_dose_per100 double precision
)